newproject/channel/urls.py
from django.urls import path
from . import views

app_name = 'channel'

urlpatterns = [
    path('', views.channel_list, name="list"),
    path('create/', views.channel_create, name="create"),
    path('my_channel/', views.my_channel, name="myChannel"),

    path('update/<int:channel_id>', views.update_channel, name="update"),
    path('delete/<int:channel_id>', views.delete_channel, name="delete"),
    path('<slug:slug>/', views.channel_detail, name="detail"),
]

newproject/charts/urls.py
from django.urls import path
from . import views

app_name = 'charts'

urlpatterns = [
    path('', views.index, name='index'),
]

newproject/newproject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from channel import views as channel_view
from restframework.api import UserList, UserDetail, UserAuthentication

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('channel/', include('channel.urls')),
    path('charts/', include('charts.urls')),
    path('djangoRT/', include('djangoRT.urls')),

    re_path(r'api/users_list/$', UserList.as_view(), name='user_list'),
    re_path(r'api/users_list/(?P<username>\d+)/$', UserDetail.as_view(), name='user_detail'),
    re_path(r'api/auth/$', UserAuthentication.as_view(), name='User Authentication API'),

    path('about', views.about, name="about"),
    path('', views.index, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newproject/channel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Channel(models.Model):
    class Meta:
        db_table = 'channel'
    name = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    metadata = models.FileField(blank=True)
    location = models.CharField(max_length=120)
    date = models.DateField(auto_now_add=True)
    soil = models.CharField(max_length=120)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def snippet(self):
        return self.description[:50] + '...'

class Comment(models.Model):
    class Meta:
        db_table = 'comment'
    channelname = models.ForeignKey(Channel, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.channelname.name, self.name)

newproject/channel/forms.py
from django.forms import ModelForm
from . models import Channel, Comment

class CreateChannel(ModelForm):
    class Meta:
        model = Channel
        fields = ['name', 'slug', 'description', 'metadata', 'location', 'soil']

class CreateComment(ModelForm):
	class Meta:
		model = Comment
		fields = ['name', 'body']

newproject/channel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Channel, Comment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . forms import CreateChannel, CreateComment

def channel_list(request):
    channel = Channel.objects.all().order_by('date')
    return render(request, 'channel/channel_list.html', {'channel': channel})

def channel_detail(request,slug):
    #return HttpResponse(slug)
    channel = Channel.objects.get(slug=slug)

    if request.method == 'POST':
        form = CreateComment(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.channelname = channel
            obj.save()

            return redirect('channel:detail', slug=channel.slug)
    else:
        form = CreateComment()

    context = {
        'channel' : channel,
        'form' : form,
    }

    return render(request, 'channel/channel_detail.html', context)

@login_required(login_url="/accounts/login/")
def my_channel(request):
    channel = Channel.objects.filter(author=request.user)
    return render(request, 'channel/my_channel.html', {'channel': channel})

@login_required(login_url="/accounts/login/")
def channel_create(request):
    if request.method == 'POST':
        form = CreateChannel(request.POST, request.FILES)
        if form.is_valid():
            # save channel to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('channel:myChannel')
    else:
        form = CreateChannel()
    return render(request, "channel/channel_create.html", {'form':form})

@login_required(login_url="/accounts/login/")
def update_channel(request, channel_id):
    channel_id = int(channel_id)
    try:
        channel_sel = Channel.objects.get(id=channel_id)
    except Channel.DoesNotExist:
        return redirect('channels:myChannel')
    form = CreateChannel(request.POST or None, instance=channel_sel)
    if form.is_valid():
        form.save()
        return redirect('channel:myChannel')
    return render(request, 'channel/channel_create.html', {'form': form})

def delete_channel(request, channel_id):
    channel_id = int(channel_id)
    try:
        channel_sel = Channel.objects.get(id = channel_id)
    except Channel.DoesNotExist:
        return redirect('channel:myChannel')
    channel_sel.delete()
    return redirect('channel:myChannel')

newproject/channel/templates/channel/channel_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-channel">
        <h2>Channel Registration</h2>
        <form class="site-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" name="Submit">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

newproject/channel/templates/channel/channel_detail.html
{% extends 'nav.html' %}

{% block content %}

    <section class="page-banner-area page-about">
        <div class="overlay"></div>
        <!-- Content -->
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 col-md-12 col-12 text-center">
                    <div class="page-banner-content">
                        <h1 class="display-4 font-weight-bold">{{ channel.name }}</h1>
                        <p>{{ channel.description }}</p>
                        <p>{{ channel.soil }}</p>
                        <p>{{ channel.location }}</p>
                        <p>{{ channel.date }}</p>
                    </div>
                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </section>

<br></br>

    <section class="banner-area py-7">
        <!-- Content -->
        <div class="container">
            <div class="row  align-items-center">
                <div class="col-md-12 col-lg-7 text-center text-lg-left">
                    <div class="main-banner">
                        <!-- Heading -->
                        <h1>Comments</h1>

                        {% if not channel.comments.all %}
                        No comment yet for this channel.

                        {% else %}
                            {% for comment in channel.comments.all %}
                                <strong>
                                    {{ comment.name }} - 
                                    {{ comment.date_added }}
                                </strong>
                                <br/>
                                {{ comment.body }}
                                <br/>
                            {% endfor %}
                        {% endif %}

                        <form method="post" action=".">
                            {% csrf_token %}

                            {{ form.as_table }}

                            <input type="submit" name="Add comment">


                        </form>

                    </div>
                </div>

                
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </section>




{% endblock %}

newproject/channel/templates/channel/channel_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Channel list</h1>
    {% csrf_token %}
    <div class="channels">
        {% for channel in channel %}
            <div class="channel">
                <h2><a href="{% url 'channel:detail' slug=channel.slug %}">{{channel.name}}</a></h2>
                <p>{{channel.snippet}}</p>
                <p>{{channel.date}}</p>
                <p class="author">added by {{channel.author.username}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

newproject/channel/templates/channel/my_channel.html
{% extends 'nav.html' %}

{% block content %}
    <h1>My Channel</h1>
    {% csrf_token %}
    <table class="table table-bordered">
    <thead class="alert-warning">
        <tr>
            <th>Channel Name</th>
            <th>Description</th>
            <th>Last Update</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for channel in channel %}
        <tr>
            <td><a href="{% url 'channel:detail' slug=channel.slug %}">{{channel.name}}</a></td>
            <td>{{ channel.snippet }}</td>
            <td>{{ channel.date }}</td>
            <td>
                <center>
                    <a href="{% url 'channel:update' channel.id %}" class="btn btn-warning" id = '{{channel.id}}'>edit</a>
                    <a href="{% url 'channel:delete' channel.id %}" class="btn btn-danger" id = '{{channel.id}}'>delete</a>
                </center>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}