newproject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

newproject/charts/urls.py
from django.urls import path
from . import views

app_name = 'charts'

urlpatterns = [
    path('', views.index, name='index'),
]

newproject/newproject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from channel import views as channel_view
from restframework.api import UserList, UserDetail, UserAuthentication

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('channel/', include('channel.urls')),
    path('charts/', include('charts.urls')),
    path('djangoRT/', include('djangoRT.urls')),

    re_path(r'api/users_list/$', UserList.as_view(), name='user_list'),
    re_path(r'api/users_list/(?P<username>\d+)/$', UserDetail.as_view(), name='user_detail'),
    re_path(r'api/auth/$', UserAuthentication.as_view(), name='User Authentication API'),

    path('about', views.about, name="about"),
    path('', views.index, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newproject/accounts/models.py
from django.db import models

class Account(models.Model):
    class Meta:
        db_table = 'Account'
    email = models.EmailField(max_length=150)
    username = models.CharField(max_length=150)
    password = models.CharField(max_length=150)

    def __str__(self):
        return self.username

newproject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
import requests
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Account
from django.contrib.auth.hashers import make_password

import json


URL = "http://127.0.0.1:8001"

def get_token():
    # Get auth Token
    url = f"{URL}/api/auth/"
    response = requests.post(url, data={'username': 'mafiqamir',
                                        'password': 'password'})
    return response.json()

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log user in
            login(request, user)
            return redirect('channels:myChannel')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        url = f"{URL}/api/users_list"
        token = get_token()
        header = {'Authorization': f'Token {token}'}
        response = requests.get(url, headers=header)
        data = response.json()

        for datas in data:
            trainee_id = datas['id']
            pwd = datas['Password']
            encrypted = make_password(pwd, salt=None, hasher='default')

            new_user = User(
                id=trainee_id,
                email=datas['Email'],
                username=datas['Username'],
                password=encrypted
            )
            new_user.save()

        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('channel:myChannel')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login2.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

newproject/accounts/templates/accounts/login.html
{% extends 'nav.html' %}

{% block content %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login - DetectGreen</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->  
    <link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->  
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->  
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
    
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-55 p-r-55 p-t-178" action="{% url 'accounts:login' %}" method="post">
                    <span class="login100-form-title">
                        Sign In
                    </span>

                    {% csrf_token %}
                    {{form}}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}">
                    {% endif %}

                    <div class="text-right p-t-13 p-b-23">
                        <span class="txt1">
                        
                        </span>

                        <a href="#" class="txt2">
                            
                        </a>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit" value="Login">
                            Sign in
                        </button>
                    </div>

                    <div class="flex-col-c p-t-170 p-b-40">
                        <span class="txt1 p-b-9">
                            Don’t have an account?
                        </span>

                        <a href="http://127.0.0.1:8001" class="txt3">
                            Sign up now
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    
<!--===============================================================================================-->
    <script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>
{% endblock %}

newproject/accounts/templates/accounts/login2.html
{% extends 'nav.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
    <em>If you don't have an account go here <a href="http://127.0.0.1:8001">Register</a> </em>
{% endblock %}

newproject/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}