newproject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

newproject/channel/urls.py
from django.urls import path
from . import views

app_name = 'channel'

urlpatterns = [
    path('', views.channel_list, name="list"),
    path('create/', views.channel_create, name="create"),
    path('my_channel/', views.my_channel, name="myChannel"),

    path('update/<int:channel_id>', views.update_channel, name="update"),
    path('delete/<int:channel_id>', views.delete_channel, name="delete"),
    path('<slug:slug>/', views.channel_detail, name="detail"),
]

newproject/charts/urls.py
from django.urls import path
from . import views

app_name = 'charts'

urlpatterns = [
    path('', views.index, name='index'),
]

newproject/djangoRT/urls.py
from django.urls import path
from . import views

app_name = 'djangoRT'

urlpatterns = [
    path('', views.index, name='index'),
]

newproject/newproject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from channel import views as channel_view
from restframework.api import UserList, UserDetail, UserAuthentication

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('channel/', include('channel.urls')),
    path('charts/', include('charts.urls')),
    path('djangoRT/', include('djangoRT.urls')),

    re_path(r'api/users_list/$', UserList.as_view(), name='user_list'),
    re_path(r'api/users_list/(?P<username>\d+)/$', UserDetail.as_view(), name='user_detail'),
    re_path(r'api/auth/$', UserAuthentication.as_view(), name='User Authentication API'),

    path('about', views.about, name="about"),
    path('', views.index, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newproject/templates/about.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="it">
  <meta name="keywords" content="Rapoo,creative, agency, startup,onepage, clean, modern,business, company,it">
  
  <meta name="author" content="themefisher.com">

  <title>DetectGreen</title>

  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="{% static 'index/plugins/bootstrap/css/bootstrap.min.css' %}">
  <!-- Animate Css -->
  <link rel="stylesheet" href="{% static 'index/plugins/animate-css/animate.css' %}">
  <!-- Icon Font css -->
  <link rel="stylesheet" href="{% static 'index/plugins/fontawesome/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'index/plugins/fonts/Pe-icon-7-stroke.css' %}">
  <!-- Themify icon Css -->
  <link rel="stylesheet" href="{% static 'index/plugins/themify/css/themify-icons.css' %}">
  <!-- Slick Carousel CSS -->
  <link rel="stylesheet" href="{% static 'index/plugins/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'index/plugins/slick-carousel/slick/slick-theme.css' %}">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="{% static 'index/css/style.css' %}">

</head>


<body id="top-header">
<!-- LOADER TEMPLATE -->
<div id="page-loader">
    <div class="loader-icon fa fa-spin colored-border"></div>
</div>
 <!-- /LOADER TEMPLATE -->


    <!-- NAVBAR
    ================================================= -->
    <nav class="navbar navbar-expand-lg navbar-dark trans-navigation fixed-top navbar-togglable">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <h3>DetectGreen</h3>
            </a>
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <!-- Links -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <a href="{% url 'channel:list' %}" class="nav-link js-scroll-trigger">
                            Channel
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a href="{% url 'djangoRT:index' %}" class="nav-link js-scroll-trigger">
                            Soil PH graph
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a href="{% url 'about' %}" class="nav-link js-scroll-trigger">
                            About
                        </a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a href="{% url 'channel:myChannel' %}" class="nav-link js-scroll-trigger">
                          My Channel
                      </a>
                    </li>

                    <ul class="ml-lg-auto list-unstyled m-0">
                    <li>
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-white btn-circled" type="submit">Logout</button>
                    </form>
                    </li>
                    {% else %}
                   <ul class="ml-lg-auto list-unstyled m-0">
                        <li><a href="{% url 'accounts:login' %}" class="btn btn-white btn-circled">Login</a></li>
                    </ul>
                    {% endif %}
                </ul>
            </div> <!-- / .navbar-collapse -->
        </div> <!-- / .container -->
    </nav>
    

   <!-- HERO
    ================================================== -->
    <section class="page-banner-area page-about">
        <div class="overlay"></div>
        <!-- Content -->
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 col-md-12 col-12 text-center">
                    <div class="page-banner-content">
                        <h1 class="display-4 font-weight-bold">Plantation Information System With IoT (DetectGreen)</h1>
                        <p>A platform that helps iGrow student to make their own research about farming using technology and to introduce Malaysian farmers to 4.0 technology.</p>
                    </div>
                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </section>



<section class="section" id="process">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 text-center">
                    <div class="section-heading">
                        <!-- Heading -->
                        <h2 class="section-title">
                            Working process
                        </h2>

                        <!-- Subheading -->
                        <p>
                            These are steps of how to start your own research.
                        </p>

                    </div>
                </div>
            </div> <!-- / .row -->

            <div class="row justify-content-center">
                <div class="col-lg-4 col-sm-6 col-md-6">
                    <div class="process-block">
                        <img src="{% static 'index/images/process/process-1.jpg' %}" alt="" class="img-fluid">

                        <h3>Channels</h3>
                        <p>First, create your own channel to start making your own research. You can have as many channels as you can to start your own. You must login first using your iGrow knowledge account and click create channel to start.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-md-6">
                    <div class="process-block">
                        <img src="{% static 'index/images/process/process-2.jpg' %}" alt="" class="img-fluid">

                        <h3>IoT Sensor</h3>
                        <p>To connect your sensor first you must login and then connect to this url 'ws://localhost:8000/ws/polData/' to get your result.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-md-6">
                    <div class="process-block">
                        <img src="{% static 'index/images/process/process-3.jpg' %}" alt="" class="img-fluid">

                        <h3>Discussion</h3>
                        <p>You can discuss and exchange idea through comment in the specific channel that you choose.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


 

 <footer class="section " id="footer">
        <div class="overlay footer-overlay"></div>
        <!--Content -->
            <div class="row text-right pt-5">
                <div class="col-lg-12">
                    <!-- Copyright -->
                    <p class="footer-copy ">
                        &copy; Copyright <span class="current-year">Themefisher</span> All rights reserved.
                    </p>
                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </footer>


    <!--  Page Scroll to Top  -->

    <a class="scroll-to-top js-scroll-trigger" href="#top-header">
        <i class="fa fa-angle-up"></i>
    </a>


   


    <!-- 
    Essential Scripts
    =====================================-->

    
    <!-- Main jQuery -->
    <script src="{% static 'index/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.1 -->
    <script src="{% static 'index/plugins/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'index/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'index/plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <script src="{% static 'index/js/jquery.easing.1.3.js' %}"></script>
    <!-- Map Js -->
    <script src="{% static 'index/plugins/google-map/gmap3.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwIQh7LGryQdDDi-A603lR8NqiF3R_ycA"></script>

    <script src="{% static 'index/js/form/contact.js' %}"></script>
    <script src="{% static 'index/js/theme.js' %}"></script>

  </body>
  </html>
   

newproject/templates/base_layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IOT</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
</head>
<body>
    <div class="container">
    <header class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"/> </a> </h1>
        <nav>
            <ul>
                <li><a href="{% url 'channel:list' %}">Channels</a></li>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'channel:create' %}" class="highlight">New Channel</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>

                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">

        {% block content %}
        {% endblock %}
    </div>
    </div>
</body>
</html>

newproject/templates/homepage.html
{% extends 'base_layout2.html' %}

{% block content %}
<!doctype html>
<html lang="en">
<head>
    {% csrf_token %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to IOT-Web Based Agriculture Information System</p>
</body>
</html>

{% endblock %}

newproject/templates/nav.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="it">
  <meta name="keywords" content="Rapoo,creative, agency, startup,onepage, clean, modern,business, company,it">
  
  <meta name="author" content="themefisher.com">

  <title>DetectGreen</title>

  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="{% static 'index/plugins/bootstrap/css/bootstrap.min.css' %}">
  <!-- Animate Css -->
  <link rel="stylesheet" href="{% static 'index/plugins/animate-css/animate.css' %}">
  <!-- Icon Font css -->
  <link rel="stylesheet" href="{% static 'index/plugins/fontawesome/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'index/plugins/fonts/Pe-icon-7-stroke.css' %}">
  <!-- Themify icon Css -->
  <link rel="stylesheet" href="{% static 'index/plugins/themify/css/themify-icons.css' %}">
  <!-- Slick Carousel CSS -->
  <link rel="stylesheet" href="{% static 'index/plugins/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'index/plugins/slick-carousel/slick/slick-theme.css' %}">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="{% static 'index/css/style.css' %}">

</head>


<body id="top-header">
<!-- LOADER TEMPLATE -->
<div id="page-loader">
    <div class="loader-icon fa fa-spin colored-border"></div>
</div>
 <!-- /LOADER TEMPLATE -->


    <!-- NAVBAR
    ================================================= -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary main-nav navbar-togglable rounded-radius">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <h3>DetectGreen</h3>
            </a>
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <!-- Links -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <a href="{% url 'channel:list' %}" class="nav-link js-scroll-trigger">
                            Channel
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a href="{% url 'djangoRT:index' %}" class="nav-link js-scroll-trigger">
                            Soil PH graph
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a href="{% url 'about' %}" class="nav-link js-scroll-trigger">
                            About
                        </a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a href="{% url 'channel:create' %}" class="nav-link js-scroll-trigger">
                          New Channel
                      </a>
                    </li>
                    
                    <ul class="ml-lg-auto list-unstyled m-0">
                    <li>
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-white btn-circled" type="submit">Logout</button>
                    </form>
                    </li>
                    {% else %}
                   <ul class="ml-lg-auto list-unstyled m-0">
                        <li><a href="{% url 'accounts:login' %}" class="btn btn-white btn-circled">Login</a></li>
                    </ul>
                    {% endif %}
                </ul>
            </div> <!-- / .navbar-collapse -->
        </div> <!-- / .container -->
    </nav>

    {% block content %}
    {% endblock %}

    <!-- 
    Essential Scripts
    =====================================-->

    
    <!-- Main jQuery -->
    <script src="{% static 'index/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.1 -->
    <script src="{% static 'index/plugins/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'index/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'index/plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <script src="{% static 'index/js/jquery.easing.1.3.js' %}"></script>
    <!-- Map Js -->
    <script src="{% static 'index/plugins/google-map/gmap3.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwIQh7LGryQdDDi-A603lR8NqiF3R_ycA"></script>

    <script src="{% static 'index/js/form/contact.js' %}"></script>
    <script src="{% static 'index/js/theme.js' %}"></script>

  </body>
  </html>
   